//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nbi_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant
    {
        public int id { get; set; }
        public string fname { get; set; }
        public string mname { get; set; }
        public string lname { get; set; }
        public System.DateTime birthday { get; set; }
        public string gender { get; set; }
        public string civil_status { get; set; }
        public string highest_education { get; set; }
        public string landline_number { get; set; }
        public string mobile_number { get; set; }
        public string email { get; set; }
        public string complexion { get; set; }
        public string peculiarities { get; set; }
        public string religion { get; set; }
        public double height { get; set; }
        public double weight { get; set; }
        public string image { get; set; }
    }
}
