//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nbi_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int id { get; set; }
        public int application_id { get; set; }
        public string branch { get; set; }
        public System.DateTime date { get; set; }
        public string valid_id { get; set; }
        public string id_number { get; set; }
    }
}
