//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nbi_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relationship
    {
        public int id { get; set; }
        public int applicant_id { get; set; }
        public string name { get; set; }
        public string name_of_father { get; set; }
        public string place_of_birth1 { get; set; }
        public string name_of_mother { get; set; }
        public string place_of_birth2 { get; set; }
    }
}
